{% set name = "particle-tracking-manager" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/particle_tracking_manager-{{ version }}.tar.gz
  sha256: 8b22fed8734e1926658b465c4e2b1c6fec16867cf0f23624929e83a11414541d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.9
    - appdirs
    - kerchunk
    - numpy
    - opendrift >=1.11.13
    - pandas
    - xarray

test:
  imports:
    - particle_tracking_manager
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/particle-tracking-manager
  summary: Manager for particle tracking simulations.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
