{% set name = "particle-tracking-manager" %}
{% set version = "0.11.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/particle_tracking_manager-{{ version }}.tar.gz
  sha256: e5ba1cd76c19edfde29d119b3cc244e2c02faeb97e706382026ca676dbcfe1cb

build:
  entry_points:
    - ptm=particle_tracking_manager.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.9
    - appdirs
    - importlib_resources
    - kerchunk ==0.2.7
    - numpy
    - opendrift >=1.11.13,<=1.13.0
    - pandas
    - xarray

test:
  imports:
    - particle_tracking_manager
  commands:
    - pip check
    - ptm --help
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/particle-tracking-manager
  summary: Manager for particle tracking simulations.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
