{% set name = "particle-tracking-manager" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/particle_tracking_manager-{{ version }}.tar.gz
  sha256: 3fac3d7620cd6449f98a7221faeaf87a46c1422bcd9c4f74179e64dbf8bfdda0

build:
  entry_points:
    - ptm=particle_tracking_manager.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.11
    - adios_db
    - aiohttp
    - appdirs
    - dask-core
    - fastparquet
    - importlib_resources
    - kerchunk ==0.2.7
    - matplotlib-base
    - netcdf4
    - numpy
    - opendrift ==1.13.0
    - pandas
    - pip
    - pydantic
    - requests
    - scipy
    - xarray
    - zarr <3.0.0

test:
  imports:
    - particle_tracking_manager
  commands:
    - pip check
    - ptm --help
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/particle-tracking-manager
  summary: Manager for particle tracking simulations.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
