{% set name = "particle-tracking-manager" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/particle_tracking_manager-{{ version }}.tar.gz
  sha256: c0aff5f6bab17025718353885edb70dc0983fb1d37899e7e84e322deee8c8808

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - appdirs
    - kerchunk
    - numpy
    - opendrift >=1.11.13
    - pandas
    - xarray

test:
  imports:
    - particle_tracking_manager
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/axiom-data-science/particle-tracking-manager
  summary: Manager for particle tracking simulations.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
